#server.servlet.context-path=/srs
#server.port=9090
#spring.datasource.url=jdbc:mysql://172.21.0.3:3306/srs_db
#spring.datasource.url=jdbc:mysql://localhost:3306/srs_db
#spring.datasource.url=jdbc:mysql://mysqldb:3306/srs_db
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#spring.datasource.initialization-mode=always
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server.port: 7003
server.error.include-message: always
spring.application.name: schr

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srs_db
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


logging:
  level:
    org.springframework.web: trace
    guru.springframework.controllers: trace
    org.hibernate: trace
    com.metadata: trace

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring:
  config:
    activate:
      on-profile: docker
server.port: 8080
spring.datasource.url: jdbc:mysql://mysqldb:3306/srs_db

---
spring:
  config:
    activate:
      on-profile: linode
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server.port: 8080