
server.port: 7003
server.error.include-message: always
spring.application.name: registration-service
#spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srs_db
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


logging:
  level:
    org.springframework.web: error
    guru.springframework.controllers: error
    org.hibernate: error
    com.metadata: error

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

---
spring:
  config:
    activate:
      on-profile: docker
server.port: 8080
spring.datasource.url: jdbc:mysql://mysqldb:3306/srs_db

---
spring:
  config:
    activate:
      on-profile: linode
  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server.port: 8080