apiVersion: v1
kind: Service
metadata:
  name: registration-app-mysql
  labels:
    app: registration-app
spec:
  ports:
  - port: 3306
  selector:
    app: registration-app
    tier: mysql
  clusterIP: None
