apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-service-deployments
  namespace: apis-services
  labels:
    application: registration-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: registration-service
      namespace: apis-services
  template:
    metadata:
      #annotations:
      #vault.hashicorp.com/agent-init-first: 'true'
      #vault.hashicorp.com/agent-inject: 'true'
      #vault.hashicorp.com/role: bozobooks-app
      #vault.hashicorp.com/agent-inject-secret-config: bozobooks/data/googleapi-config
      #vault.hashicorp.com/agent-inject-template-config: |
      # {{ with secret "bozobooks/data/googleapi-config" -}}
      #  export googleapikey="{{ .Data.data.googleapikey }}"
      #{{- end }} 
      labels:
        app: registration-service
        namespace: apis-services
    spec:
      containers:
      - name: registration-service
        image: hossamgbm/metadata_srs-app:5
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "linode"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: mysql-user-password
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-server
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-database-name
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config-map
              key: mysql-user-username
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "300Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/info
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 20
          successThreshold: 1
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
