apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: gateway-rate-limit
  annotations:
   kubernetes.io/ingress.class: kong
config: 
  second: 5
  minute: 10
  policy: local
  limit_by: path
  path: /api/v1/*
plugin: rate-limiting
